services:
    _defaults:
        autowire: true
        autoconfigure: true

    Shopsys\Cdn\:
        resource: '../../**/*{Facade,Factory,Listener,Collector}.php'
        exclude: '../../{DependencyInjection,Resources,Twig}'

    Shopsys\FrameworkBundle\Component\Collector\ShopsysFrameworkDataCollector:
        class: Shopsys\Cdn\Component\Collector\ShopsysFrameworkDataCollector
        tags:
            - { name: data_collector, id: shopsys_framework_core, template: '@ShopsysFramework/Components/Collector/shopsysFramework.html.twig', priority: -300 }

    Shopsys\Cdn\Component\Domain\Domain:
        factory: ['@Shopsys\Cdn\Component\Domain\DomainFactory', createWithCdn]
        arguments:
            - '%shopsys.domain_config_filepath%'
            - '%shopsys.domain_urls_config_filepath%'
            - '%env(CDN_DOMAIN)%'
        lazy: true

    Shopsys\Cdn\Component\Image\ImageFacade:
        arguments: ['%shopsys.image_url_prefix%']
        calls:
            - { method: setCdnDomain, arguments: ['%env(CDN_DOMAIN)%'] }

    Shopsys\Cdn\Twig\:
        resource: '../../Twig/'

    Shopsys\Cdn\Twig\LocalizationExtension:
        arguments:
            - '%shopsys.web_dir%'

    Shopsys\FrameworkBundle\Component\Domain\Domain: '@Shopsys\Cdn\Component\Domain\Domain'

    Shopsys\FrameworkBundle\Twig\LocalizationExtension: '@Shopsys\Cdn\Twig\LocalizationExtension'

    Shopsys\FrameworkBundle\Component\Image\ImageFacade: '@App\Component\Image\ImageFacade'

    Shopsys\FrameworkBundle\Model\Localization\LocalizationListener: '@Shopsys\Cdn\Model\Localization\LocalizationListener'
