services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Shopsys\FrameworkBundle\Component\Domain\Domain: '@Shopsys\Cdn\Component\Domain\Domain'

    Shopsys\Cdn\Component\Domain\Domain:
        factory: ['@Shopsys\Cdn\Component\Domain\DomainFactoryOverwritingDomainUrl', create]
        arguments:
            - '%shopsys.domain_config_filepath%'
            - '%shopsys.domain_urls_config_filepath%'
        lazy: true

    Shopsys\Cdn\Component\Domain\DomainFactoryOverwritingDomainUrl:
        class: Shopsys\Cdn\Component\Domain\DomainFactoryOverwritingDomainUrl
        arguments:
            - '%overwrite_domain_url%'
